# Generated by Django 3.2.7 on 2022-05-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('pk',)},
        ),
    ]
